### ISSUE TITLE
some permission issues

### ISSUE THREAD

**Issue by hugo-blue** [ingonyama-zk/zk-benchmarks#1]
While testing this flow, we encountered two issues: 
1) We cannot access the existing database because INGO_BENCHMARKS_DB_PASSWORD is unknown. 
2) We are unable to access https://docs.google.com/presentation/d/1Fxs34TuPmix6cejpqKrX1NYrxf2ExYK7LYH6OkGUkSU/edit?usp=share_link.

**Comment by omershlo** [comment]
thanks @hugo-blue 
cc: @svpolonsky @LeonHibnik @ImmanuelSegol

**Comment by svpolonsky** [comment]
(1) I enabled password-less read-only access to guest_user
(2) I allowed all with the link to view https://docs.google.com/presentation/d/1Fxs34TuPmix6cejpqKrX1NYrxf2ExYK7LYH6OkGUkSU/edit?usp=share_link.

Please let me know if this solves this issue

**Comment by svpolonsky** [comment]
Issue resolved
